apiVersion: v1
kind: ConfigMap
metadata:
  name: rustypotato-config
  labels:
    app: rustypotato
data:
  rustypotato.toml: |
    [server]
    port = 6379
    bind_address = "0.0.0.0"
    max_connections = 10000
    tcp_keepalive = true
    tcp_nodelay = true

    [storage]
    aof_enabled = true
    aof_path = "/data/rustypotato.aof"
    aof_fsync = "everysec"
    max_memory = "2GB"
    eviction_policy = "lru"

    [logging]
    level = "info"
    format = "json"

    [metrics]
    enabled = true
    port = 9090
    path = "/metrics"

    [security]
    auth_enabled = false
    tls_enabled = false