apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustypotato-pvc
  namespace: rustypotato
  labels:
    app: rustypotato
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd  # Adjust based on your cluster's storage classes